### Recover info from pokemon ditto
GET http://localhost:3000/pokemon/ditto

### Create a pokemon
POST http://localhost:3000/pokemon
Content-Type: application/json

{
    "name": "ditto",
    "type": "normal",
    "moves": [
        "transform"
    ]
}